version: '3.6'
services:
  telegraf:
    image: telegraf:1.16.3-alpine
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '${IP}:8125:8125/udp'

  influxdb:
    image: influxdb:1.8-alpine
    env_file: .env
    ports:
      - '${IP}:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:7.3.4
    depends_on:
      - influxdb
    env_file: .env
    links:
      - influxdb
    ports:
      - '${IP}:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
  
  proxy:
    image: nginx
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - grafana
      - influxdb

volumes:
  grafana_data: {}
  influxdb_data: {}

configs:
  nginx:
    file: ./nginx.conf
